# Generated by Django 5.2.14 on 2026-06-05 22:38

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import saleor.core.utils.json_serializer
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0027_channel_allow_legacy_gift_card_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar_url', models.URLField(blank=True, default='', max_length=512)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.blogcategory')),
            ],
            options={
                'verbose_name_plural': 'blog categories',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('private_metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('metadata', models.JSONField(blank=True, db_default={}, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('content', models.JSONField(blank=True, null=True)),
                ('featured_comments', models.JSONField(blank=True, help_text='Structured list of curated/static comments.', null=True)),
                ('featured_image', models.URLField(blank=True, default='', max_length=512)),
                ('reading_time_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogauthor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.blogtag')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPostChannelListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_listings', to='blog.blogpost')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_listings', to='channel.channel')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='BlogPostTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=35)),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.blogpost')),
            ],
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='blogcategory_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='blogcategory_meta_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blogpostchannellisting',
            unique_together={('blog_post', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='blogposttranslation',
            unique_together={('language_code', 'blog_post')},
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='blogpost_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='blogpost_meta_idx'),
        ),
    ]
